# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '窗口.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NERprogram(object):
    def setupUi(self, NERprogram):
        NERprogram.setObjectName("NERprogram")
        NERprogram.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(NERprogram)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(60, 50, 660, 81))
        self.textEdit.setStyleSheet("font: 16pt \"宋体\";")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 200, 54, 12))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 220, 660, 301))
        self.textBrowser.setStyleSheet("font: 16pt \"宋体\";")
        self.textBrowser.setObjectName("textBrowser")
        NERprogram.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NERprogram)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        NERprogram.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NERprogram)
        self.statusbar.setObjectName("statusbar")
        NERprogram.setStatusBar(self.statusbar)

        self.retranslateUi(NERprogram)
        self.pushButton.clicked.connect(NERprogram.slot_button)
        QtCore.QMetaObject.connectSlotsByName(NERprogram)

    def retranslateUi(self, NERprogram):
        _translate = QtCore.QCoreApplication.translate
        NERprogram.setWindowTitle(_translate("NERprogram", "命名实体识别系统"))
        self.textEdit.setHtml(_translate("NERprogram", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("NERprogram", "确定"))
        self.label.setText(_translate("NERprogram", "请输入句子(中文）："))
        self.label_2.setText(_translate("NERprogram", "实体："))
